language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-expressed' ]; then cd .. && eval "mv $currentfolder generator-expressed" && cd generator-expressed; fi

